name: deploy

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Check style, format and lint
      run: |
        poetry run mypy .
        poetry run yapf --diff --recursive **/*.py
        poetry run flake8 .                                                     
        poetry run pylint ./* 
    - name: Tests
      run: |
        PYTHONPATH=. poetry run pytest -n auto
        PYTHONPATH=. poetry run mamba . 
